/* This file is automatically generated.
   This file selects the right generated file of `__stub_FUNCTION' macros
   based on the architecture being compiled for.  */


#ifndef LIBC32
    #define __stub___compat_bdflush
    #define __stub_chflags
    #define __stub_fchflags
    #define __stub_gtty
    #define __stub_lchmod
    #define __stub_revoke
    #define __stub_setlogin
    #define __stub_sigreturn
    #define __stub_sstk
    #define __stub_stty
#endif
